{
  imports = [
    ./blink-indent
    ./cellular-automaton
    ./cinnamon-nvim
    ./fidget-nvim
    ./highlight-undo
    ./hlargs-nvim
    ./indent-blankline
    ./neoscroll-nvim
    ./nvim-cursorline
    ./nvim-scrollbar
    ./nvim-web-devicons
    ./rainbow-delimiters
    ./satellite-nvim
    ./syntax-gaslighting
    ./tiny-devicons-auto-colors
  ];
}
