
files.extend-exclude = ["npins/sources.json"]
default.extend-ignore-words-re = [
  "(?i)(noice)",
  "befores",
  "annote",
  "viw",
  "typ",
  "edn",
  "esy",
  "BA", # somehow "BANanaD3V" is valid, but BA is not...
  "Emac",
  "tese", # for glsl shaders
  "Caue",
  "bse", # ./modules/plugins/tabline/nvim-bufferline/nvim-bufferline.nix:20:78: "bse" should be "base".
]

