{
  imports = [
    ./angular-language-server.nix
    ./arduino-language-server.nix
    ./asm-lsp.nix
    ./astro-language-server.nix
    ./basedpyright.nix
    ./bash-language-server.nix
    ./ccls.nix
    ./clangd.nix
    ./clojure-lsp.nix
    ./csharp_ls.nix
    ./cue.nix
    ./dart.nix
    ./deno.nix
    ./docker-language-server.nix
    ./elixir-ls.nix
    ./elm-language-server.nix
    ./emmet-ls.nix
    ./fish-lsp.nix
    ./fsautocomplete.nix
    ./gleam.nix
    ./glsl_analyzer.nix
    ./gopls.nix
    ./harper.nix
    ./helm-ls.nix
    ./intelephense.nix
    ./jdt-language-server.nix
    ./jinja-lsp.nix
    ./jq-lsp.nix
    ./julia-languageserver.nix
    ./just-lsp.nix
    ./kotlin-language-server.nix
    ./lemminx.nix
    ./lua-language-server.nix
    ./markdown-oxide.nix
    ./marksman.nix
    ./millet.nix
    ./neocmakelsp.nix
    ./nil.nix
    ./nimlsp.nix
    ./nixd.nix
    ./nushell.nix
    ./ocaml-lsp.nix
    ./ols.nix
    ./omnisharp.nix
    ./openscad-lsp.nix
    ./phan.nix
    ./phpactor.nix
    ./pyrefly.nix
    ./pyright.nix
    ./python-lsp-server.nix
    ./qmlls.nix
    ./r-languageserver.nix
    ./roslyn-ls.nix
    ./ruby-lsp.nix
    ./ruff.nix
    ./rumdl.nix
    ./solargraph.nix
    ./some-sass-language-server.nix
    ./sqls.nix
    ./superhtml.nix
    ./svelte-language-server.nix
    ./tailwindcss-language-server.nix
    ./taplo.nix
    ./terraform-ls.nix
    ./texlab.nix
    ./tinymist.nix
    ./tofu-ls.nix
    ./tombi.nix
    ./twig-language-server.nix
    ./ty.nix
    ./typescript-go.nix
    ./typescript-language-server.nix
    ./vala-language-server.nix
    ./vhdl-ls.nix
    ./vscode-css-language-server.nix
    ./vscode-json-language-server.nix
    ./vtsls.nix
    ./vue-language-server.nix
    ./wgsl-analyzer.nix
    ./yaml-language-server.nix
    ./zls.nix
    ./zuban.nix
  ];
}
