name: 🚀 Feature Request
description: "Propose a new feature"
title: "<short description of the desired addition>"
labels: [feature-request]
body:
  - type: checkboxes
    attributes:
      label: I have verified that this feature request has not been made before
      description: >-
        Before opening a new issue for feature requests, please consider searching through currently
        open issues [here](https://github.com/notashelf/nvf/issues). If you would like to discuss a
        new addition beforehand, you may first want to create a new discussion threat and discuss it
        with the maintainers [on the discussions tab](https://github.com/notashelf/nvf/discussions)
      options:
        - required: true
          label: >-
            I have checked the [issues tab](https://github.com/notashelf/nvf/issues?q=is%3Aissue),
            and did not find a similar feature request. I understand that my issue will be closed
            if it is a duplicate.

  - type: dropdown
    id: feature-area
    attributes:
      label: Feature Type
      description: Please describe the kind of addition this is
      multiple: true
      options:
        - New Plugin
        - Update Request (Plugin/Nixpkgs)
        - Documentation Updates
        - Other
    validations:
      required: true


  - type: textarea
    id: feature-description
    attributes:
      label: Feature description
      description: >-
        Please provide a clear and concise description of the desired addition. If this is a plugin
        addition, please also include a link to the desired plugin and the reason why you think this
        is a good addition. Keep in mind that we may refuse plugin requests as nvf already provides
        appropriate methods of installing plugins in user configurations.
      placeholder: >-
        "nvf currently does [...], which really frustrates me" or "You should add [...] because I think
        [...]"
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: >-
        If you have tried anything before creating this issue, please give us a clear and concise
        description of any alternative solutions or methods you have considered.
      placeholder: "I have considered [...]"
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: >-
        If there is anything else you would like to mention, such as additional context or screenshots
        demonstrating the requested feature, please add them here. This field is optional, but you may
        be requested to provide further context. Please ensure that your feature request clearly describes
        the requested feature in good detail.
    validations:
      required: false
