[[sec-release-0.5]]
== Release 0.5


[[sec-release-0.5-changelog]]
=== Changelog


https://github.com/horriblename[horriblename]:

* Added transparency support for tokyonight theme.

* Fixed a bug where cmp's close and scrollDocs mappings wasn't working.

* Streamlined and simplified extra plugin API with the addition of <<opt-vim.extraPlugins>>

* Allow using command names in place of LSP packages to avoid automatic installation.

https://github.com/amanse[amanse]:

* Added daily notes options for obsidian plugin.

* Added jdt-language-server for Java.

https://github.com/yavko[yavko]:

* Added Deno Language Server for javascript/typescript

https://github.com/notashelf[notashelf]:

* Added GitHub Copilot to completion sources.

* Added <<opt-vim.ui.borders>> for global and individual plugin border configuration.

* LSP integrated breadcrumbs with <<opt-vim.ui.breadcrumbs>> through nvim-navic

* LSP navigation helper with nvim-navbuddy, depends on nvim-navic (automatically enabled)

* Addeed nvim-navic integration for catppuccin theme

* Fixed mismatching zig language description

* Added support for `statix` and `deadnix` through <<opt-vim.languages.nix.extraDiagnostics.types>>

* Added lsp_lines plugin for showing diagnostic messages

* Added a configuration option for choosing the leader key

* The package used for neovim is now customizable by the user, using <<opt-vim.package>>. For best results, always use an unwrapped package.
