.TH "nvf" "5" "January 1, 1980" "nvf"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" enable line breaks after slashes
.cflags 4 /

.SH "NAME"
nvf \- Configuration specification for the nvf.

.SH "DESCRIPTION"
The nvf configuration specification provides a declarative structure for configuring Neovim using Nix with few
lines of Nix. This document outlines the available options and their usage to create modular, reusable, and
reproducible configurations using nvf's module system options. For tips, tricks and possible quirks with available
plugins please visit https://notashelf.github.io/nvf/
