.Dd January 1, 1980
.Dt neovim-flake 1
.Os neovim-flake
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" enable line breaks after slashes
.cflags 4 /
.Sh NAME
.Nm neovim-flake
.Nd A highly modular, extensible and distro-agnostic Neovim distribution for Nix/NixOS.
.
.Sh BUGS
.Pp
Please report any bugs that you might encounter on the
\m[blue]\fBproject issue tracker\fR\m[]\&.

.Sh SEE ALSO
.Pp
\fBneovim-flake\fR(5)

.Sh AUTHOR
.Pp
\fBneovim-flake contributors\fR
.RS 4
Author.
.RE

.Sh COPYRIGHT
.br
Copyright \(co 2023\(en2024 neovim-flake contributors
.br
