.Dd January 1, 1980
.Dt nvf 1
.Os nvf
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" enable line breaks after slashes
.cflags 4 /
.Sh NAME
.Nm nvf
.Nd A highly modular, extensible and distro-agnostic Neovim configuration framework for Nix/NixOS.
.
.Sh BUGS
.Pp
Please report any bugs that you might encounter on the
\m[blue]\fBproject issue tracker\fR\m[]\&.

.Sh SEE ALSO
.Pp
\fBnvf\fR(5)

.Sh AUTHOR
.Pp
\fBnvf contributors\fR
.RS 4
Author.
.RE

.Sh COPYRIGHT
.br
Copyright \(co 2023\(en2024 nvf contributors
.br
