.Dd January 1, 1980
.Dt neovim-flake 1
.Os neovim-flake
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" enable line breaks after slashes
.cflags 4 /
.Sh NAME
.Nm neovim-flake
.Nd a extensible and distro-agonistic Neovim configuration wrapper in Nix
.
.Sh BUGS
.Pp
Please report any bugs on the
\m[blue]\fBproject issue tracker\fR\m[]\&.

.Sh AUTHOR
.Pp
\fBneovim-flake contributors\fR
.RS 4
Author.
.RE

.Sh COPYRIGHT
.br
Copyright \(co 2017\(en2022 neovim-flake contributors
.br
