# frozen_string_literal: true

source "https://rubygems.org"
gem "rubocop"
gem "rubocop-rails"
gem "rubocop-rspec"     
gem "rubocop-minitest"
gem "rubocop-sequel"
gem "rubocop-rake"
gem "rubocop-graphql"
gem "rubocop-capybara"
gem "rubocop-factory_bot"
gem "rubocop-performance"
# gem "rails"
