name: Cleanup
on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 1 * *" # 4AM on 1st of every month
    - cron: "0 4 15 * *" # 4AM on the 15th of every month
jobs:
  branches:
    name: Cleanup old branches
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Delete old branches"
        uses: beatlabs/delete-old-branches-action@v0.0.10
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          date: "1 months ago"
          dry_run: false
          delete_tags: false
          exclude_open_pr_branches: true
